apiVersion: v1
kind: Pod
metadata:
  name: saf-configmap-env-demo
spec:
  containers:
    - name: configmap-demo
      image: alpine
      command: ["sleep", "3600"]
      env:
        # Define the environment variable
        - name: PLAYER_LIVES # Define env variable for each properties
          valueFrom:
            configMapKeyRef: # for configmap use this keyref
              name: saf-player-pro-demo  # The ConfigMap this value should be on configured configmap.
              key: player_lives # The key to fetch.
        - name: PROPERTIES_FILE_NAME  # Define env variable for each properties
          valueFrom:
            configMapKeyRef:
              name: saf-player-pro-demo  # The ConfigMap this value should be on configured configmap.
              key: properties_file_name  # The key to fetch.
        - name: SECRET_USERNAME  # Define env variable for each properties
          valueFrom:
            secretKeyRef:  # for secret use this keyref
              name: example-secret  # The secret this value should be on configured configmap.
              key: username
        - name: SECRET_PASSWORD  # Define env variable for each properties
          valueFrom:
            secretKeyRef:
              name: example-secret
              key: password

  # execute on singlenode
  # env variables : passing config or secret data using env variables to containers.
  # for env variables we have create/define env variables for each properties.

  # Steps 
  # Go to Directory
  # go to vi editor and copy the above content
  # save and exit
  # create pods and env variables kubectl apply -f <filename.yaml>
  # Check pods is created, kubectl get pods
  # login or get inside the deployed container, kubectl exec <name-of the pod> -it -- sh
  # for alphine container is sh, for linux, rhel..../bin/bash or /bin/sh
  # will get inside the container, execute below command to get env variable values
  # / # echo $PLAYER_LIVES
  # 5
  # / # echo $PROPERTIES_FILE_NAME
  # user-interface.properties
  # / #
  # / # echo $SECRET_USERNAME
  # YWRtaW4=
  # / #
  # To print all env variables
  # / # printenv
  # PLAYER_LIVES=5
  # KUBERNETES_PORT=tcp://10.96.0.1:443
  # KUBERNETES_SERVICE_PORT=443
  # HOSTNAME=saf-configmap-env-demo
  # put exit to exit from containers
  # / # exit


